import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import MainSession from '../components/MainSession'
import BackedBy from '../components/BackedBy'
import EveryThingYouNeed from '../components/EveryThingYouNeed'
import TradeAndEarn from '../components/TradeAndEarn'
import Join from '../components/Join'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
      <Nav />
      </header>
      <MainSession />
      <BackedBy />
      <EveryThingYouNeed />
      <TradeAndEarn />
      <Join />
    </div>
  )
}
